version: '3.1'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
    restart: always
    links:
      - database
    networks:
      - property-connection

  database:
    image: 'mongo'
    container_name: database
    environment:
      - MONGO_INITDB_DATABASE='property-protection'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    restart: always
    networks:
      - property-connection

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    networks:
      - property-connection

networks:
  property-connection:
    driver: bridge
